name: ğŸ³ Build & Push telegram-forwarder

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    name: ğŸ›  Build and Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: ğŸ”½ Checkout source
        uses: actions/checkout@v4

      - name: ğŸ” Login to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: ğŸ³ Build & Push
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          echo "ğŸ“¦ Building and pushing: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
